### ISSUE TITLE
Routes imported from compat package instead of react-router-dom

### ISSUE THREAD

**Issue by cseas** [SyMind/react-router-dom-5-to-6#2]
The readme mentions that the `upgrade-switch-to-routes` transform will import `Router` from `react-router-dom`.
But running the below command added all `Routes` import from the compat package.

```sh
npx react-router-dom-5-to-6@0.0.2 src --transform=upgrade-switch-to-routes
```

## Current behavior

```diff
- import { Switch, Route } from 'react-router-dom';
+ import { Route } from 'react-router-dom';
+ import { Routes } from 'react-router-dom-5-to-6-compat';
```

## Expected behavior

```diff
- import { Switch, Route } from 'react-router-dom';
+ import { Routes, Route } from 'react-router-dom';
```

**Comment by SyMind** [comment]
`Routes` do not support absolute paths in `react-router-dom` v6, so the codemod replaces it with compatible one. You should replace it to origin `Routes` before you replace all paths as relative paths.

Here is more detail: https://github.com/remix-run/react-router/issues/8035

**Comment by cseas** [comment]
Thanks! I'll check it out. Looks like the behaviour of the codemod is intended so closing this issue.

**Comment by cseas** [comment]
Thanks! I'll check it out. Looks like the behaviour of the codemod is intended so closing this issue.
